#!/bin/sh
# Install files to an Android device keeping the semantic of install(1)
#echo "$0 $*"
while : ; do
	case $1 in
		""|"-c")
			;;
		"-d")
			isdir=1
			;;
		"-m")
			shift
			mode=${1}
			;;
		*)
			files="${files} ${last}"
			last=${1}
			;;
	esac
	! shift && break
done

test "$isdir" = "1" && ((mkdir -p ${files} ${last} && exit 0) || exit 1)

for file in $files; do
	base=`basename "${file}"`
	echo "${file} -> device:${last}/${base}"
	${ADB} push "${file}" "${last}/${base}" 2>/dev/null
	test $? != 0 && exit $?

	test -n "${mode}" && ${ADB} shell chmod ${mode} ${last}/${base}
done

exit 0
